### ISSUE TITLE
Support for Puppy Linux

### ISSUE THREAD

**Issue by sc0ttj** [Cyclenerd/postinstall#12]
Puppy Linux has a command-line package manager available called `Pkg` (command `pkg`).

https://gitlab.com/sc0ttj/Pkg

**Comment by Cyclenerd** [comment]
I've never used Puppy Linux. In the Wiki (http://wikka.puppylinux.com/PPM) I found that `ppm` is the default package manager. I'd rather support the standard if there is one.

**Comment by sc0ttj** [comment]
PPM is not command line, cannot be called to install stuff programatically - you literally have to click around the GUI .. `pkg` is the de-facto cli package manager in Puppy Linux.

**Comment by Cyclenerd** [comment]
Added with https://github.com/Cyclenerd/postinstall/pull/13
