### ISSUE TITLE
Support for Mageia

### ISSUE THREAD

**Issue by Cyclenerd** [Cyclenerd/postinstall#7]
Detect and support Mageia Linux distribution with `urpmi` package manager.

**Comment by ghost** [comment]
I would like to add Mageia support!

**Comment by Cyclenerd** [comment]
Thank you. You are welcome to submit a pull with a `base/MAGEIA` folder and a `README.md`. Then you won't need many more for your free Hacktoberfest T-shirt.

**Comment by Cyclenerd** [comment]
https://github.com/Cyclenerd/postinstall/commit/54cb424ece89a49b98bbeff45506273a39a94aa1
